import json
import logging
from collections.abc import Mapping
from typing import Protocol
from uuid import UUID

import httpx

from app.ai.schemas import AnalystContext, AnalystResult, Evidence

logger = logging.getLogger(__name__)

ANALYST_SYSTEM_PROMPT = """You are Sentinel Mission Analyst. Analyze completed or active simulated UAV mission data.
Make factual claims only from Sentinel internal tool results. Compare timestamps,
vehicle identifiers, states, and metrics carefully. Distinguish observation from
inference, cite supporting event IDs, and state when data is insufficient.
You are strictly read-only: do not issue commands, modify missions or waypoints,
alter simulation state, initiate failures, control vehicles, or provide weapon,
targeting, strike, or autonomous-engagement guidance. Keep recommendations limited
to software and simulation configuration.
Return only JSON matching the requested structured response.
"""


class AnalystProviderError(Exception):
    pass


class AnalystProviderUnavailable(AnalystProviderError):
    pass


class MissionAnalystProvider(Protocol):
    name: str
    model: str | None

    async def analyze(self, run_id: UUID, user_message: str, context: AnalystContext) -> AnalystResult:
        ...


def _evidence_from_context(context: AnalystContext) -> list[Evidence]:
    evidence: list[Evidence] = []
    for event in context.mission_events:
        try:
            evidence.append(
                Evidence(
                    event_id=event["id"],
                    vehicle_id=event.get("vehicle_id"),
                    sim_time_ms=event["sim_time_ms"],
                )
            )
        except (KeyError, TypeError, ValueError):
            continue
        if len(evidence) >= 20:
            break
    return evidence


class MockMissionAnalystProvider:
    name = "mock"
    model = "sentinel-mock-analyst-v1"

    async def analyze(self, run_id: UUID, user_message: str, context: AnalystContext) -> AnalystResult:
        normalized = user_message.casefold()
        unsafe_terms = (
            "weapon",
            "targeting",
            "strike",
            "firing",
            "engagement",
            "attack",
        )
        if any(term in normalized for term in unsafe_terms):
            return AnalystResult(
                run_id=run_id,
                answer="I can only analyze benign simulated mission operations and software behavior. I cannot provide weapon, targeting, strike, or autonomous-engagement guidance.",
                confidence="high",
                limitations=["The requested topic is outside Sentinel's safety boundary."],
                provider=self.name,
                model=self.model,
            )

        summary = context.run_summary
        events = context.mission_events
        evidence = _evidence_from_context(context)
        critical = [event for event in events if event.get("severity") == "CRITICAL"]
        warnings = [event for event in events if event.get("severity") == "WARNING"]
        if critical:
            lead = critical[0]
            answer = (
                f"The run received {summary.get('telemetry_messages_received', 0)} telemetry messages across "
                f"{summary.get('vehicle_count', 0)} vehicles. The highest-severity observed incident was "
                f"{lead.get('event_type', 'unknown')} at {lead.get('sim_time_ms', 0)} ms."
            )
            confidence = "high"
        elif warnings:
            lead = warnings[0]
            answer = (
                f"The run completed with {summary.get('warning_count', 0)} warning-level events and no "
                f"critical events in the retrieved sample. The first warning was {lead.get('event_type', 'unknown')}."
            )
            confidence = "medium"
        else:
            answer = (
                f"The run contains {summary.get('vehicle_count', 0)} vehicles and "
                f"{summary.get('telemetry_messages_received', 0)} persisted telemetry messages. "
                "No warning or critical event was present in the bounded event sample."
            )
            confidence = "medium" if events else "low"
        limitations = []
        if not events:
            limitations.append("No persisted mission events were available for explanation.")
        limitations.append("This response is generated by the deterministic offline mock provider.")
        sections = {
            "Mission Summary": f"{summary.get('vehicle_count', 0)} vehicles; {summary.get('mission_duration_ms', 0)} ms simulated duration.",
            "Completion": f"{summary.get('completed_vehicle_count', 0)} of {summary.get('vehicle_count', 0)} vehicles completed.",
            "Communications": f"Observed availability was {summary.get('communications_availability_percent', 0.0):.1f}%.",
            "System Performance": f"Telemetry p95 latency was {summary.get('latency_p95_ms', 0.0):.1f} ms.",
            "Key Events": f"{summary.get('event_count', 0)} persisted events; {summary.get('critical_count', 0)} critical.",
            "Observations": answer,
        }
        return AnalystResult(
            run_id=run_id,
            answer=answer,
            confidence=confidence,
            evidence=evidence,
            limitations=limitations,
            provider=self.name,
            model=self.model,
            sections=sections,
        )


class DisabledMissionAnalystProvider:
    name = "disabled"
    model = None

    async def analyze(self, run_id: UUID, user_message: str, context: AnalystContext) -> AnalystResult:
        raise AnalystProviderUnavailable("Mission Analyst is disabled")


class GeminiMissionAnalystProvider:
    name = "gemini"

    def __init__(self, api_key: str, model: str = "gemini-2.0-flash") -> None:
        self.api_key = api_key
        self.model = model

    async def analyze(self, run_id: UUID, user_message: str, context: AnalystContext) -> AnalystResult:
        payload = {
            "system_instruction": {"parts": [{"text": ANALYST_SYSTEM_PROMPT}]},
            "contents": [{"role": "user", "parts": [{"text": json.dumps({"run_id": str(run_id), "question": user_message, "context": context.model_dump(mode="json")})}]}],
            "generationConfig": {"responseMimeType": "application/json"},
        }
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent"
        try:
            async with httpx.AsyncClient(timeout=20.0) as client:
                response = await client.post(url, params={"key": self.api_key}, json=payload)
                response.raise_for_status()
                body: Mapping[str, object] = response.json()
        except (httpx.HTTPError, ValueError) as exc:
            logger.warning("Gemini Mission Analyst request failed", extra={"error": str(exc)})
            raise AnalystProviderUnavailable("Mission Analyst provider is temporarily unavailable") from exc
        try:
            candidates = body["candidates"]
            text = candidates[0]["content"]["parts"][0]["text"]  # type: ignore[index]
            parsed = json.loads(text)
            result = AnalystResult.model_validate({"run_id": run_id, "provider": self.name, "model": self.model, **parsed})
        except (KeyError, IndexError, TypeError, ValueError, json.JSONDecodeError) as exc:
            raise AnalystProviderError("Mission Analyst returned invalid structured output") from exc
        return result


def provider_for(name: str, api_key: str | None) -> MissionAnalystProvider:
    normalized = name.casefold()
    if normalized == "mock":
        return MockMissionAnalystProvider()
    if normalized == "disabled":
        return DisabledMissionAnalystProvider()
    if normalized == "gemini":
        if not api_key:
            raise AnalystProviderUnavailable("Gemini provider is not configured")
        return GeminiMissionAnalystProvider(api_key)
    raise AnalystProviderUnavailable(f"Unsupported Mission Analyst provider: {name}")
