"""create mission and run schema

Revision ID: 8b28d94d876b
Revises: 
Create Date: 2026-08-12 03:17:14.579728
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '8b28d94d876b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'RUNNING', 'PAUSED', 'COMPLETED', 'ABORTED', name='missionstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('network_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_latency_ms', sa.Double(), nullable=False),
    sa.Column('jitter_ms', sa.Double(), nullable=False),
    sa.Column('packet_loss_percent', sa.Double(), nullable=False),
    sa.Column('duplicate_percent', sa.Double(), nullable=False),
    sa.Column('disconnect_probability', sa.Double(), nullable=False),
    sa.Column('disconnect_duration_min_ms', sa.Integer(), nullable=False),
    sa.Column('disconnect_duration_max_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('callsign', sa.String(length=100), nullable=False),
    sa.Column('vehicle_type', sa.String(length=100), nullable=False),
    sa.Column('max_speed_mps', sa.Double(), nullable=False),
    sa.Column('cruise_speed_mps', sa.Double(), nullable=False),
    sa.Column('battery_capacity', sa.Double(), nullable=False),
    sa.Column('telemetry_rate_hz', sa.Double(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callsign')
    )
    op.create_table('mission_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_definition_id', sa.Uuid(), nullable=False),
    sa.Column('starting_latitude', sa.Double(), nullable=True),
    sa.Column('starting_longitude', sa.Double(), nullable=True),
    sa.Column('starting_altitude_m', sa.Double(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_definition_id'], ['vehicle_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'vehicle_definition_id', name='uq_mission_vehicle_definition')
    )
    op.create_table('simulation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'RUNNING', 'PAUSED', 'COMPLETED', 'ABORTED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('simulation_speed', sa.Double(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debriefs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('structured_result', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_vehicles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_definition_id', sa.Uuid(), nullable=False),
    sa.Column('starting_latitude', sa.Double(), nullable=True),
    sa.Column('starting_longitude', sa.Double(), nullable=True),
    sa.Column('starting_altitude_m', sa.Double(), nullable=True),
    sa.Column('network_profile_id', sa.Uuid(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['network_profile_id'], ['network_profiles.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_definition_id'], ['vehicle_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'vehicle_definition_id', name='uq_run_vehicle_definition')
    )
    op.create_table('waypoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('altitude_m', sa.Double(), nullable=False),
    sa.Column('target_speed_mps', sa.Double(), nullable=True),
    sa.Column('arrival_radius_m', sa.Double(), nullable=True),
    sa.Column('action', sa.Enum('TRANSIT', 'HOLD', 'SURVEY', 'RETURN', name='waypointaction', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['mission_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'vehicle_id', 'sequence', name='uq_waypoint_sequence')
    )
    op.create_index('ix_waypoints_mission_vehicle_sequence', 'waypoints', ['mission_id', 'vehicle_id', 'sequence'], unique=False)
    op.create_table('failure_injections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('failure_type', sa.Enum('COMMUNICATIONS_BLACKOUT', 'HIGH_LATENCY', 'PACKET_LOSS', 'GPS_QUALITY_DEGRADATION', 'BATTERY_ANOMALY', 'SENSOR_UNAVAILABLE', 'SERVICE_DELAY', name='failuretype', native_enum=False), nullable=False),
    sa.Column('started_sim_time_ms', sa.Integer(), nullable=True),
    sa.Column('ended_sim_time_ms', sa.Integer(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['run_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mission_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('MISSION_CREATED', 'MISSION_UPDATED', 'MISSION_STARTED', 'MISSION_PAUSED', 'MISSION_RESUMED', 'MISSION_COMPLETED', 'MISSION_ABORTED', 'VEHICLE_READY', 'VEHICLE_LAUNCHED', 'VEHICLE_WAYPOINT_REACHED', 'VEHICLE_RETURNING', 'VEHICLE_LANDED', 'VEHICLE_COMPLETED', 'VEHICLE_TELEMETRY', 'COMMUNICATIONS_DEGRADED', 'COMMUNICATIONS_STALE', 'COMMUNICATIONS_LOST', 'COMMUNICATIONS_RECOVERING', 'COMMUNICATIONS_RESTORED', 'BATTERY_LOW', 'BATTERY_CRITICAL', 'FAILURE_INJECTED', 'FAILURE_CLEARED', 'SYSTEM_WARNING', 'SYSTEM_ERROR', name='eventtype', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='eventseverity', native_enum=False), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('sim_time_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['run_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_run_time', 'mission_events', ['run_id', 'sim_time_ms'], unique=False)
    op.create_index('ix_events_run_type', 'mission_events', ['run_id', 'event_type'], unique=False)
    op.create_index('ix_events_run_vehicle_time', 'mission_events', ['run_id', 'vehicle_id', 'sim_time_ms'], unique=False)
    op.create_table('telemetry_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('sim_time_ms', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('altitude_m', sa.Double(), nullable=True),
    sa.Column('heading_deg', sa.Double(), nullable=True),
    sa.Column('ground_speed_mps', sa.Double(), nullable=True),
    sa.Column('battery_percent', sa.Double(), nullable=True),
    sa.Column('mission_state', sa.Enum('IDLE', 'READY', 'LAUNCHING', 'TRANSIT', 'EXECUTING', 'RETURNING', 'LANDED', 'COMPLETE', 'PAUSED', 'ABORTED', name='vehiclemissionstate', native_enum=False), nullable=True),
    sa.Column('communications_state', sa.Enum('HEALTHY', 'DEGRADED', 'STALE', 'DISCONNECTED', 'RECOVERING', name='communicationsstate', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['simulation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['run_vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'vehicle_id', 'sequence', name='uq_telemetry_sequence')
    )
    op.create_index('ix_telemetry_run_time', 'telemetry_samples', ['run_id', 'sim_time_ms'], unique=False)
    op.create_index('ix_telemetry_run_vehicle_time', 'telemetry_samples', ['run_id', 'vehicle_id', 'sim_time_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_run_vehicle_time', table_name='telemetry_samples')
    op.drop_index('ix_telemetry_run_time', table_name='telemetry_samples')
    op.drop_table('telemetry_samples')
    op.drop_index('ix_events_run_vehicle_time', table_name='mission_events')
    op.drop_index('ix_events_run_type', table_name='mission_events')
    op.drop_index('ix_events_run_time', table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_table('failure_injections')
    op.drop_index('ix_waypoints_mission_vehicle_sequence', table_name='waypoints')
    op.drop_table('waypoints')
    op.drop_table('run_vehicles')
    op.drop_table('debriefs')
    op.drop_table('simulation_runs')
    op.drop_table('mission_vehicles')
    op.drop_table('vehicle_definitions')
    op.drop_table('network_profiles')
    op.drop_table('missions')
    # ### end Alembic commands ###

